== Contribute to this Documentation!

=== Prerequisites

* You have docker installed on your local machine (https://docs.docker.com/docker-for-mac/install/[Mac], https://docs.docker.com/docker-for-windows/install/[Windows])
* Ability to run ``make`` commands

=== Distributed Documentation

The documentation for SDP is distributed across multiple repositories in order to keep the documentation next to the code.  This greatly helps with ensuring documentation remains up to date by enforcing the documentation is maintained during Pull Request reviews. 

The rest of this documentation outlines how to contribute to the main SDP Documentation site. 

Both the  https://github.com/jenkinsci/templating-engine-plugin[Jenkins Templating Engine]
and https://github.com/boozallen/sdp-libraries[SDP Pipeline Libraries] repositories will have 
documentation that explains how to contribute to those respective sites. 

=== Local Development

There is a ``Makefile`` at the root of the https://github.com/boozallen/sdp-docs[SDP Documentation Repository] that automates some tasks to aide in local development of this documentation: 

[%header,cols=2*]
.Local Development Commands
|===
|Command
|Description

|``make html``
|Builds the documentation locally.  Open ``./docs/html/index.html`` to see the resulting docs

|``make html live``
|Runs a hot-reload server to see the documentation updated as changes are made on ``http://localhost:8000``

|``make user=<github username> token=<github pat> html deploy``
|When run from the ``master`` branch, if you have write permissions to the SDP Documentation Repository, this will deploy the docs.
|===

=== Submitting Contributions

SDP follows the Fork and Pull workflow for accepting contributions from contributors. 

The content for this site can be found in the ``pages`` directory of the repository. 

Images should be added to the ``images`` directory. 

==== Steps to Contribute

1. Fork the https://github.com/boozallen/sdp-docs[SDP Documentation Repository] 
2. Make changes to your own fork of the repository 
3. Create a Pull Request from your fork to the main repository
4. Fill out the Pull Request Template describing your changes 

Lambda School has produced a great https://lambdaschool.com/the-commons/how-to-fork-and-contribute-to-a-project-using-git[tutorial] that explains the Fork and Pull model in more detail. 