= Add Credentials to Jenkins

In Jenkins, credentials are used to allow the Jenkins instance to
interact with 3rd party applications and websites.

While there are several kinds of credentials in Jenkins, we will only be
working with global credentials, which can be used from anywhere within
the Jenkins instance.

The steps to add credentials to your Jenkins instance are as follows:

[arabic]
. On the Jenkins Homepage, click *Credentials* *>* *System* on the left.
. In *System*, click the text *Global credentials (unrestricted)* within
the centered table under the domain header.
. On the left, click *Add Credentials*.
. Click the dropdown labeled *Kind* and select *Username with password*
if it's not already selected.
. Click the dropdown labeled *Scope* and select *Global (Jenkins, nodes,
items, all child items, etc)* if it's not already selected.
. Enter the values for the *Username*, *Password*, and *ID* fields as
denoted by the sections that require a Jenkins credential be added.
. Click the *OK* button.
. Verify that the credential that you just created can now be seen in
the list of credentials with the correct name.
